// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKkyLUyCgBEWOfq0Gs7Yfv5FLWiZgVV1I',
    appId: '1:853054702494:web:2e30c6d1cb702c29a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-GEJ09LYWM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2yNxEEZ2QKHWnEuUsxOiDH9Yv74ZHko',
    appId: '1:853054702494:android:b802786d8aa7f2d2a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:3e5a9960611885fda30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-378emiflr6at5testppt5hm2al2bc11c.apps.googleusercontent.com',
    iosClientId: '853054702494-10b5pfgd0qrii3qiirt9tbrngcprsd31.apps.googleusercontent.com',
    iosBundleId: 'com.zappq.driver.app',
  );
}
