import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';  // For kIsWeb

import 'app.dart'; // Your App widget

// Import your Firebase options (web, android, and ios options)
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase based on the platform
  if (kIsWeb) {
    // For Web, use the web-specific FirebaseOptions
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.web,
    );
  } else if (defaultTargetPlatform == TargetPlatform.android) {
    // For Android, use the android-specific FirebaseOptions
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.android,
    );
  } else if (defaultTargetPlatform == TargetPlatform.iOS) {
    // For iOS, use the iOS-specific FirebaseOptions
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.ios,
    );
  }

  runApp(App());
}
